# Generated by Django 4.2.19 on 2025-04-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_id_alter_position_id_alter_voter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
